#!/usr/bin/env bash
set -Eeo pipefail

CONFIG_TEMPLATE_PATH="/usr/share/mhserveremu/Config.ini.template"
CONFIG_OUTPUT_PATH="/usr/share/mhserveremu/Config.ini"

FRONTEND_BIND_IP=${FRONTEND_BIND_IP:="127.0.0.1"}
FRONTEND_PORT=${FRONTEND_PORT:="4306"}
FRONTEND_PUBLIC_ADDRESS=${FRONTEND_PUBLIC_ADDRESS:="127.0.0.1"}
WEBFRONTEND_ADDRESS=${WEBFRONTEND_ADDRESS:="localhost"}
WEBFRONTEND_PORT=${WEBFRONTEND_PORT:="8080"}
WEBFRONTEND_ENABLE_LOGING_RATE_LIMIT=${WEBFRONTEND_ENABLE_LOGING_RATE_LIMIT:="false"}
PLAYERMANAGER_USE_JSON_DB_MANAGER=${PLAYERMANAGER_USE_JSON_DB_MANAGER:="false"}
PLAYERMANAGER_NEWS_URL=${PLAYERMANAGER_NEWS_URL:="http://localhost/news"}
DBMANAGER_MAX_BACKUP_NUMBER=${DBMANAGER_MAX_BACKUP_NUMBER:="5"}
DBMANAGER_BACKUP_INTERVAL_MINUTES=${DBMANAGER_BACKUP_INTERVAL_MINUTES:="15"}
GAMEDATA_LOAD_ALL_PROTOTYPES=${GAMEDATA_LOAD_ALL_PROTOTYPES:="false"}
GAMEDATA_USE_EQUIPMENT_SLOT_TABLE_CACHE=${GAMEDATA_USE_EQUIPMENT_SLOT_TABLE_CACHE:="false"}
CUSTOMGAMEOPTIONS_AUTO_UNLOCK_AVATARS=${CUSTOMGAMEOPTIONS_AUTO_UNLOCK_AVATARS:="true"}
CUSTOMGAMEOPTIONS_AUTO_UNLOCK_TEAMUPS=${CUSTOMGAMEOPTIONS_AUTO_UNLOCK_TEAMUPS:="true"}
CUSTOMGAMEOPTIONS_ALLOW_SAME_GROUP_TALENTS=${CUSTOMGAMEOPTIONS_ALLOW_SAME_GROUP_TALENTS:="false"}
CUSTOMGAMEOPTIONS_DISABLE_INSTANCED_LOOT=${CUSTOMGAMEOPTIONS_DISABLE_INSTANCED_LOOT:="false"}
CUSTOMGAMEOPTIONS_DISABLE_ACCOUNT_BINDING=${CUSTOMGAMEOPTIONS_DISABLE_ACCOUNT_BINDING:="false"}
CUSTOMGAMEOPTIONS_DISABLE_CHARACTER_BINDING=${CUSTOMGAMEOPTIONS_DISABLE_CHARACTER_BINDING:="true"}
CUSTOMGAMEOPTIONS_USE_PRESTIGE_LOOT_TABLE=${CUSTOMGAMEOPTIONS_USE_PRESTIGE_LOOT_TABLE:="false"}
MTXSTORE_GAZILLIONITE_BALANCE_FOR_NEW_ACCOUNTS=${MTXSTORE_GAZILLIONITE_BALANCE_FOR_NEW_ACCOUNTS:="10000"}
MTXSTORE_ES_TO_GAZILLIONITE_CONVERSION_RATIO=${MTXSTORE_ES_TO_GAZILLIONITE_CONVERSION_RATIO:="2.25"}
MTXSTORE_ES_TO_GAZILLIONITE_CONVERSION_STEP=${MTXSTORE_ES_TO_GAZILLIONITE_CONVERSION_STEP:="4"}
MTXSTORE_GIFTING_OMEGA_LEVEL_REQUIRED=${MTXSTORE_GIFTING_OMEGA_LEVEL_REQUIRED:="0"}
MTXSTORE_GIFTING_INFINITY_LEVEL_REQUIRED=${MTXSTORE_GIFTING_INFINITY_LEVEL_REQUIRED:="0"}
MTXSTORE_HOME_PAGE_URL=${MTXSTORE_HOME_PAGE_URL:="http://localhost/store"}
MTXSTORE_HOME_BANNER_PAGE_URL=${MTXSTORE_HOME_BANNER_PAGE_URL:="http://localhost/store/images/banner.png"}
MTXSTORE_HEROES_BANNER_PAGE_URL=${MTXSTORE_HEROES_BANNER_PAGE_URL:="http://localhost/store/images/banner.png"}
MTXSTORE_COSTUMES_BANNER_PAGE_URL=${MTXSTORE_COSTUMES_BANNER_PAGE_URL:="http://localhost/store/images/banner.png"}
MTXSTORE_BOOSTS_BANNER_PAGE_URL=${MTXSTORE_BOOSTS_BANNER_PAGE_URL:="http://localhost/store/images/banner.png"}
MTXSTORE_CHESTS_BANNER_PAGE_URL=${MTXSTORE_CHESTS_BANNER_PAGE_URL:="http://localhost/store/images/banner.png"}
MTXSTORE_SPECIALS_BANNER_PAGE_URL=${MTXSTORE_SPECIALS_BANNER_PAGE_URL:="http://localhost/store/images/banner.png"}
MTXSTORE_REAL_MONEY_URL=${MTXSTORE_REAL_MONEY_URL:="https://localhost/MTXStore/AddG"}
MTXSTORE_REWRITE_ORIGINAL_BUNDLE_URLS=${MTXSTORE_REWRITE_ORIGINAL_BUNDLE_URLS:="true"}
MTXSTORE_BUNDLE_INFO_URL=${MTXSTORE_BUNDLE_INFO_URL:="http://localhost/bundles/"}
MTXSTORE_BUNDLE_IMAGE_URL=${MTXSTORE_BUNDLE_IMAGE_URL:="http://localhost/bundles/images/"}

populate_template() {
    sed -i \
        -e "s/%%FRONTEND_BIND_IP%%/${FRONTEND_BIND_IP}/g" \
        -e "s/%%FRONTEND_PORT%%/${FRONTEND_PORT}/g" \
        -e "s/%%FRONTEND_PUBLIC_ADDRESS%%/${FRONTEND_PUBLIC_ADDRESS}/g" \
        -e "s/%%WEBFRONTEND_ADDRESS%%/${WEBFRONTEND_ADDRESS}/g" \
        -e "s/%%WEBFRONTEND_PORT%%/${WEBFRONTEND_PORT}/g" \
        -e "s/%%WEBFRONTEND_ENABLE_LOGING_RATE_LIMIT%%/${WEBFRONTEND_ENABLE_LOGING_RATE_LIMIT}/g" \
        -e "s/%%PLAYERMANAGER_USE_JSON_DB_MANAGER%%/${PLAYERMANAGER_USE_JSON_DB_MANAGER}/g" \
        -e "s,%%PLAYERMANAGER_NEWS_URL%%,${PLAYERMANAGER_NEWS_URL},g" \
        -e "s/%%DBMANAGER_MAX_BACKUP_NUMBER%%/${DBMANAGER_MAX_BACKUP_NUMBER}/g" \
        -e "s/%%DBMANAGER_BACKUP_INTERVAL_MINUTES%%/${DBMANAGER_BACKUP_INTERVAL_MINUTES}/g" \
        -e "s/%%GAMEDATA_LOAD_ALL_PROTOTYPES%%/${GAMEDATA_LOAD_ALL_PROTOTYPES}/g" \
        -e "s/%%GAMEDATA_USE_EQUIPMENT_SLOT_TABLE_CACHE%%/${GAMEDATA_USE_EQUIPMENT_SLOT_TABLE_CACHE}/g" \
        -e "s/%%CUSTOMGAMEOPTIONS_AUTO_UNLOCK_AVATARS%%/${CUSTOMGAMEOPTIONS_AUTO_UNLOCK_AVATARS}/g" \
        -e "s/%%CUSTOMGAMEOPTIONS_AUTO_UNLOCK_TEAMUPS%%/${CUSTOMGAMEOPTIONS_AUTO_UNLOCK_TEAMUPS}/g" \
        -e "s/%%CUSTOMGAMEOPTIONS_ALLOW_SAME_GROUP_TALENTS%%/${CUSTOMGAMEOPTIONS_ALLOW_SAME_GROUP_TALENTS}/g" \
        -e "s/%%CUSTOMGAMEOPTIONS_DISABLE_INSTANCED_LOOT%%/${CUSTOMGAMEOPTIONS_DISABLE_INSTANCED_LOOT}/g" \
        -e "s/%%CUSTOMGAMEOPTIONS_DISABLE_ACCOUNT_BINDING%%/${CUSTOMGAMEOPTIONS_DISABLE_ACCOUNT_BINDING}/g" \
        -e "s/%%CUSTOMGAMEOPTIONS_DISABLE_CHARACTER_BINDING%%/${CUSTOMGAMEOPTIONS_DISABLE_CHARACTER_BINDING}/g" \
        -e "s/%%CUSTOMGAMEOPTIONS_USE_PRESTIGE_LOOT_TABLE%%/${CUSTOMGAMEOPTIONS_USE_PRESTIGE_LOOT_TABLE}/g" \
        -e "s/%%MTXSTORE_GAZILLIONITE_BALANCE_FOR_NEW_ACCOUNTS%%/${MTXSTORE_GAZILLIONITE_BALANCE_FOR_NEW_ACCOUNTS}/g" \
        -e "s/%%MTXSTORE_ES_TO_GAZILLIONITE_CONVERSION_RATIO%%/${MTXSTORE_ES_TO_GAZILLIONITE_CONVERSION_RATIO}/g" \
        -e "s/%%MTXSTORE_ES_TO_GAZILLIONITE_CONVERSION_STEP%%/${MTXSTORE_ES_TO_GAZILLIONITE_CONVERSION_STEP}/g" \
        -e "s/%%MTXSTORE_GIFTING_OMEGA_LEVEL_REQUIRED%%/${MTXSTORE_GIFTING_OMEGA_LEVEL_REQUIRED}/g" \
        -e "s/%%MTXSTORE_GIFTING_INFINITY_LEVEL_REQUIRED%%/${MTXSTORE_GIFTING_INFINITY_LEVEL_REQUIRED}/g" \
        -e "s,%%MTXSTORE_HOME_PAGE_URL%%,${MTXSTORE_HOME_PAGE_URL},g" \
        -e "s,%%MTXSTORE_HOME_BANNER_PAGE_URL%%,${MTXSTORE_HOME_BANNER_PAGE_URL},g" \
        -e "s,%%MTXSTORE_HEROES_BANNER_PAGE_URL%%,${MTXSTORE_HEROES_BANNER_PAGE_URL},g" \
        -e "s,%%MTXSTORE_COSTUMES_BANNER_PAGE_URL%%,${MTXSTORE_COSTUMES_BANNER_PAGE_URL},g" \
        -e "s,%%MTXSTORE_BOOSTS_BANNER_PAGE_URL%%,${MTXSTORE_BOOSTS_BANNER_PAGE_URL},g" \
        -e "s,%%MTXSTORE_CHESTS_BANNER_PAGE_URL%%,${MTXSTORE_CHESTS_BANNER_PAGE_URL},g" \
        -e "s,%%MTXSTORE_SPECIALS_BANNER_PAGE_URL%%,${MTXSTORE_SPECIALS_BANNER_PAGE_URL},g" \
        -e "s,%%MTXSTORE_REAL_MONEY_URL%%,${MTXSTORE_REAL_MONEY_URL},g" \
        -e "s/%%MTXSTORE_REWRITE_ORIGINAL_BUNDLE_URLS%%/${MTXSTORE_REWRITE_ORIGINAL_BUNDLE_URLS}/g" \
        -e "s,%%MTXSTORE_BUNDLE_INFO_URL%%,${MTXSTORE_BUNDLE_INFO_URL},g" \
        -e "s,%%MTXSTORE_BUNDLE_IMAGE_URL%%,${MTXSTORE_BUNDLE_IMAGE_URL},g" \
        "$CONFIG_OUTPUT_PATH"
}

cp "$CONFIG_TEMPLATE_PATH" "$CONFIG_OUTPUT_PATH"
populate_template
exec "$@"