#!/usr/bin/env bash
set -Eeo pipefail

CONFIG_TEMPLATE_PATH="/usr/share/mhserveremu/Config.ini.template"
CONFIG_OUTPUT_PATH="/usr/share/mhserveremu/Config.ini"

FRONTEND_BIND_IP=${FRONTEND_BIND_IP:=127.0.0.1}
FRONTEND_PORT=${FRONTEND_PORT:=4306}
FRONTEND_PUBLIC_ADDRESS=${FRONTEND_PUBLIC_ADDRESS:=127.0.0.1}
AUTH_ADDRESS=${AUTH_ADDRESS:=localhost}
AUTH_PORT=${AUTH_PORT:=8080}
USE_JSON_DB_MANAGER=${USE_JSON_DB_MANAGER:=false}
MAX_BACKUP_NUMBER=${MAX_BACKUP_NUMBER:=5}
BACKUP_INTERVAL_MINUTES=${BACKUP_INTERVAL_MINUTES:=15}
LOAD_ALL_PROTOTYPES=${LOAD_ALL_PROTOTYPES:=false}
USE_EQUIPMENT_SLOT_TABLE_CACHE=${USE_EQUIPMENT_SLOT_TABLE_CACHE:=false}

populate_template() {
    sed -i \
        -e "s/%%FRONTEND_BIND_IP%%/$FRONTEND_BIND_IP/g" \
        -e "s/%%FRONTEND_PORT%%/$FRONTEND_PORT/g" \
        -e "s/%%FRONTEND_PUBLIC_ADDRESS%%/$FRONTEND_PUBLIC_ADDRESS/g" \
        -e "s/%%AUTH_ADDRESS%%/$AUTH_ADDRESS/g" \
        -e "s/%%AUTH_PORT%%/$AUTH_PORT/g" \
        -e "s/%%USE_JSON_DB_MANAGER%%/$USE_JSON_DB_MANAGER/g" \
        -e "s/%%MAX_BACKUP_NUMBER%%/$MAX_BACKUP_NUMBER/g" \
        -e "s/%%BACKUP_INTERVAL_MINUTES%%/$BACKUP_INTERVAL_MINUTES/g" \
        -e "s/%%LOAD_ALL_PROTOTYPES%%/$LOAD_ALL_PROTOTYPES/g" \
        -e "s/%%USE_EQUIPMENT_SLOT_TABLE_CACHE%%/$USE_EQUIPMENT_SLOT_TABLE_CACHE/g" \
        "$CONFIG_OUTPUT_PATH"
}

cp "$CONFIG_TEMPLATE_PATH" "$CONFIG_OUTPUT_PATH"
populate_template
exec "$@"