#!/usr/bin/env bash
set -Eeo pipefail

CONFIG_TEMPLATE_PATH="/usr/share/mhserveremu/Config.ini.template"
CONFIG_OUTPUT_PATH="/usr/share/mhserveremu/Config.ini"

FRONTEND_BIND_IP=${FRONTEND_BIND_IP:="127.0.0.1"}
FRONTEND_PORT=${FRONTEND_PORT:="4306"}
FRONTEND_PUBLIC_ADDRESS=${FRONTEND_PUBLIC_ADDRESS:="127.0.0.1"}
AUTH_ADDRESS=${AUTH_ADDRESS:="localhost"}
AUTH_PORT=${AUTH_PORT:="8080"}
NEWS_URL=${NEWS_URL:="http://localhost/news"}
USE_JSON_DB_MANAGER=${USE_JSON_DB_MANAGER:="false"}
MAX_BACKUP_NUMBER=${MAX_BACKUP_NUMBER:="5"}
BACKUP_INTERVAL_MINUTES=${BACKUP_INTERVAL_MINUTES:="15"}
LOAD_ALL_PROTOTYPES=${LOAD_ALL_PROTOTYPES:="false"}
USE_EQUIPMENT_SLOT_TABLE_CACHE=${USE_EQUIPMENT_SLOT_TABLE_CACHE:="false"}
AUTO_UNLOCK_AVATARS=${AUTO_UNLOCK_AVATARS:="true"}
AUTO_UNLOCK_TEAMUPS=${AUTO_UNLOCK_TEAMUPS:="true"}
ALLOW_SAME_GROUP_TALENTS=${ALLOW_SAME_GROUP_TALENTS:="false"}
DISABLE_INSTANCED_LOOT=${DISABLE_INSTANCED_LOOT:="false"}
DISABLE_ACCOUNT_BINDING=${DISABLE_ACCOUNT_BINDING:="false"}
DISABLE_CHARACTER_BINDING=${DISABLE_CHARACTER_BINDING:="true"}
USE_PRESTIGE_LOOT_TABLE=${USE_PRESTIGE_LOOT_TABLE:="false"}
GAZILLIONITE_BALANCE_FOR_NEW_ACCOUNTS=${GAZILLIONITE_BALANCE_FOR_NEW_ACCOUNTS:="5000"}
ES_TO_GAZILLIONITE_CONVERSION_RATIO=${ES_TO_GAZILLIONITE_CONVERSION_RATIO:="2.25"}
STORE_HOME_PAGE_URL=${STORE_HOME_PAGE_URL:="http://localhost/store"}
STORE_HOME_BANNER_PAGE_URL=${STORE_HOME_BANNER_PAGE_URL:="http://localhost/store/images/banner.png"}
STORE_HEROES_BANNER_PAGE_URL=${STORE_HEROES_BANNER_PAGE_URL:="http://localhost/store/images/banner.png"}
STORE_COSTUMES_BANNER_PAGE_URL=${STORE_COSTUMES_BANNER_PAGE_URL:="http://localhost/store/images/banner.png"}
STORE_BOOSTS_BANNER_PAGE_URL=${STORE_BOOSTS_BANNER_PAGE_URL:="http://localhost/store/images/banner.png"}
STORE_CHESTS_BANNER_PAGE_URL=${STORE_CHESTS_BANNER_PAGE_URL:="http://localhost/store/images/banner.png"}
STORE_SPECIALS_BANNER_PAGE_URL=${STORE_SPECIALS_BANNER_PAGE_URL:="http://localhost/store/images/banner.png"}
STORE_REAL_MONEY_URL=${STORE_REAL_MONEY_URL:="http://localhost/store/gs-bundles.html"}

populate_template() {
    sed -i \
        -e "s/%%FRONTEND_BIND_IP%%/${FRONTEND_BIND_IP}/g" \
        -e "s/%%FRONTEND_PORT%%/${FRONTEND_PORT}/g" \
        -e "s/%%FRONTEND_PUBLIC_ADDRESS%%/${FRONTEND_PUBLIC_ADDRESS}/g" \
        -e "s/%%AUTH_ADDRESS%%/${AUTH_ADDRESS}/g" \
        -e "s/%%AUTH_PORT%%/${AUTH_PORT}/g" \
        -e "s,%%NEWS_URL%%,${NEWS_URL},g" \
        -e "s/%%USE_JSON_DB_MANAGER%%/${USE_JSON_DB_MANAGER}/g" \
        -e "s/%%MAX_BACKUP_NUMBER%%/${MAX_BACKUP_NUMBER}/g" \
        -e "s/%%BACKUP_INTERVAL_MINUTES%%/${BACKUP_INTERVAL_MINUTES}/g" \
        -e "s/%%LOAD_ALL_PROTOTYPES%%/${LOAD_ALL_PROTOTYPES}/g" \
        -e "s/%%USE_EQUIPMENT_SLOT_TABLE_CACHE%%/${USE_EQUIPMENT_SLOT_TABLE_CACHE}/g" \
        -e "s/%%AUTO_UNLOCK_AVATARS%%/${AUTO_UNLOCK_AVATARS}/g" \
        -e "s/%%AUTO_UNLOCK_TEAMUPS%%/${AUTO_UNLOCK_TEAMUPS}/g" \
        -e "s/%%ALLOW_SAME_GROUP_TALENTS%%/${ALLOW_SAME_GROUP_TALENTS}/g" \
        -e "s/%%DISABLE_INSTANCED_LOOT%%/${DISABLE_INSTANCED_LOOT}/g" \
        -e "s/%%DISABLE_ACCOUNT_BINDING%%/${DISABLE_ACCOUNT_BINDING}/g" \
        -e "s/%%DISABLE_CHARACTER_BINDING%%/${DISABLE_CHARACTER_BINDING}/g" \
        -e "s/%%USE_PRESTIGE_LOOT_TABLE%%/${USE_PRESTIGE_LOOT_TABLE}/g" \
        -e "s/%%GAZILLIONITE_BALANCE_FOR_NEW_ACCOUNTS%%/${GAZILLIONITE_BALANCE_FOR_NEW_ACCOUNTS}/g" \
        -e "s/%%ES_TO_GAZILLIONITE_CONVERSION_RATIO%%/${ES_TO_GAZILLIONITE_CONVERSION_RATIO}/g" \
        -e "s,%%STORE_HOME_PAGE_URL%%,${STORE_HOME_PAGE_URL},g" \
        -e "s,%%STORE_HOME_BANNER_PAGE_URL%%,${STORE_HOME_BANNER_PAGE_URL},g" \
        -e "s,%%STORE_HEROES_BANNER_PAGE_URL%%,${STORE_HEROES_BANNER_PAGE_URL},g" \
        -e "s,%%STORE_COSTUMES_BANNER_PAGE_URL%%,${STORE_COSTUMES_BANNER_PAGE_URL},g" \
        -e "s,%%STORE_BOOSTS_BANNER_PAGE_URL%%,${STORE_BOOSTS_BANNER_PAGE_URL},g" \
        -e "s,%%STORE_CHESTS_BANNER_PAGE_URL%%,${STORE_CHESTS_BANNER_PAGE_URL},g" \
        -e "s,%%STORE_SPECIALS_BANNER_PAGE_URL%%,${STORE_SPECIALS_BANNER_PAGE_URL},g" \
        -e "s,%%STORE_REAL_MONEY_URL%%,${STORE_REAL_MONEY_URL},g" \
        "$CONFIG_OUTPUT_PATH"
}

cp "$CONFIG_TEMPLATE_PATH" "$CONFIG_OUTPUT_PATH"
populate_template
exec "$@"