name: Docker Image CI Nightly
on:
  push:
    branches: [ "main" ]
    paths:
      - "Dockerfile"
      - "Dockerfile.alpine"
      - "docker-entrypoint.sh"
      - "start-server"
      - "**/Config.ini.template"
      - "Makefile"
  schedule:
    - cron: '15 7 * * *'
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/docker-build-push.yml
    permissions:
      actions: write
      contents: read
      packages: write
      attestations: write
      id-token: write
    with:
      matrix: >-
        [
          {"version": "nightly",        "version_dir": "nightly", "branch": "master", "dockerfile": "Dockerfile"},
          {"version": "nightly-alpine", "version_dir": "nightly", "branch": "master", "dockerfile": "Dockerfile.alpine"}
        ]
    secrets:
      RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
