name: Tests
on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "Dockerfile"
      - "Dockerfile.alpine"
      - "docker-entrypoint.sh"
      - "start-server"
      - "**/Config.ini.template"
      - "Makefile"
      - "**/*.sh"
      - ".editorconfig"
      - ".editorconfig-checker.json"
      - ".hadolint.yaml"
permissions:
  contents: read
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # v2.0.0
        with:
          scandir: .
          ignore_names: mhserveremu-config.sh
          additional_files: docker-entrypoint.sh start-server
      - name: Hadolint — Dockerfile
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
        with:
          dockerfile: Dockerfile
      - name: Hadolint — Dockerfile.alpine
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
        with:
          dockerfile: Dockerfile.alpine
      - name: EditorConfig check
        uses: editorconfig-checker/action-editorconfig-checker@840e866d93b8e032123c23bac69dece044d4d84c # v2.2.0

  test:
    name: Image Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: '1.0.0'
          - version: '1.0.1'
          - version: 'nightly'
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up rclone
        uses: AnimMouse/setup-rclone@26ef2133e09fd383329a1d4c1fbe6a71db1976c9 # v1.12.0
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}
      - name: Download necessary files
        run: |
          rclone copy r2:private-dependencies/Calligraphy.sip ${{ github.workspace }}
          rclone copy r2:private-dependencies/mu_cdata.sip ${{ github.workspace }}
      - name: Run tests
        run: make test-${{ matrix.version }}
